### ISSUE TITLE
GData Plugin -- Won't Authenticate w/Google Correctly

### ISSUE THREAD

**Issue by brendoncdrew** [flathub/org.claws_mail.Claws-Mail#11] opened 2020-04-26 20:57 UTC
So, the GData plugin in Claws mail doesen't work because it won't correctly Authenticate with google... Says "Sign in with Google is Temporarly disabled for this App;This App has not been verified yet by google in order to use google sign in."

Seens ti be a problem with the OAuth Verification see 
 here for more info: [https://stackoverflow.com/questions/50509667/sign-in-with-google-temporarily-disabled-for-this-app](HERE)

Basiclly someone affilitated with development just needs to go sign up for oauth verification for the App/Plugin so we can actually be able to use it again.

-B

**Comment by cobratbq** [comment] 2020-04-28 17:54
Ah, this might be tricky. I construct the flatpak package from a fresh build, so this might be specific to the flatpak-package. Have you tried the same operations with a prepackaged claws-mail, for example one provided by a linux distribution?

It would help me a lot to know if this problem is specific for the flatpak-package or something general for the Claws-Mail application.

**Comment by cobratbq** [comment] 2020-06-04 21:53
In case you're still interested, you may want to check this test package: https://github.com/flathub/org.claws_mail.Claws-Mail/pull/12#issuecomment-638501266

It is rebased onto a different base image - which is not relevant for your issue - but also includes a newer version of some shared modules. One in particular, `libsecret`, may be relevant to this issue.

**Comment by jphmrst** [comment] 2020-08-15 16:27
I get that now on XUbunutu Focal, Claws Mail version 3.17.5 via apt-get.

After "Click here to open the Google authorization page in a browser", I can choose my account, but then in the browser I have Google's error "Sign in with Google temporarily disabled for this app/This app has not been verified yet by Google in order to use Google Sign In."

**Comment by cobratbq** [comment] 2020-08-18 15:05
> I get that now on XUbunutu Focal, Claws Mail version 3.17.5 via apt-get.
> 
> After "Click here to open the Google authorization page in a browser", I can choose my account, but then in the browser I have Google's error "Sign in with Google temporarily disabled for this app/This app has not been verified yet by Google in order to use Google Sign In."

Okay, that means that this issue is not caused by the flatpak-package itself, but rather is in the source code.
I suspect [Bug 4338 - GData Plugin – Won’t Authenticate w/Google ](https://www.thewildbeast.co.uk/claws-mail/bugzilla/show_bug.cgi?id=4338) is your issue.

**Comment by cobratbq** [comment] 2020-10-09 15:05
Some issues regarding OAuth authentication have been solved in Claws-Mail 3.17.7. The test-package being prepared in PR https://github.com/flathub/org.claws_mail.Claws-Mail/pull/14 should have these fixes. You can try this version - once it is built - to see if it fixes your issue.

**Comment by cobratbq** [comment] 2021-09-24 20:39
I'm closing this issue due to having no further information on whether this is still a problem, and assuming that the authentication problems are truly fixed in `3.17.7` this should not be an issue anymore.

**Comment by jvw1954** [comment] 2021-11-22 14:43
This is still an issue in Claws Mail, version 3.17.8.

**Comment by cobratbq** [comment] 2021-11-22 16:07
I'll have another look at this. Thanks for reporting.

**Comment by fred-ak** [comment] 2021-11-22 16:54
I can't use the GData Plugin with Claws-mail 3.18.0 either. OAuth2 has not been set up. Is that required?

**Comment by cobratbq** [comment] 2021-11-23 00:00
> I can't use the GData Plugin with Claws-mail 3.18.0 either. OAuth2 has not been set up. Is that required?

Yes. This is the critical step.

**Comment by fred-ak** [comment] 2021-11-23 03:40
On Mon, 22 Nov 2021 16:00:35 -0800
cobratbq ***@***.***> wrote:

> > I can't use the GData Plugin with Claws-mail 3.18.0 either. OAuth2
> > has not been set up. Is that required?  
> 
> Yes. This is the critical step.
> 

Thank you,

Fred

**Comment by cobratbq** [comment] 2021-12-07 20:17
I will close this again. The steps in the initial GData plug-in dialog need to be followed and successfully completed for Claws-Mail to get the necessary authentication. Only if completed, can Claws-Mail access the servers.

**Closed by cobratbq** 2021-12-07 20:17 UTC
